name: MCPets
main: fr.nocsy.mcpets.MCPets
version: ${version}
description: MCModels affiliate plugin. Join the workshop ! https://discord.gg/p7QTm2gUyf
depend:
  - MythicMobs
  - ModelEngine
softdepend:
  - WorldGuard
  - LuckPerms
  - PlaceholderAPI
author: Nocsy
api-version: 1.17
commands:
  mcpets:
    description: Command to manage your pets
    Usage: /mcpets
    permission: mcpets.use
    aliases: [ pets ]